import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useEffect } from "react";
import engine from "../modules/Engine";
import Matter, {  Events,  Engine, World, Bodies } from "matter-js";
const { log } = console;

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() => {
    var Engine = Matter.Engine,
    Render = Matter.Render,
    Runner = Matter.Runner,
    Bodies = Matter.Bodies,
    Composite = Matter.Composite,
    Mouse = Matter.Mouse,
    MouseConstraint = Matter.MouseConstraint;

    var engine = Engine.create();
    var render = Render.create({
      element: document.body,
      engine: engine,
      options:{
        background: "transparent",
        wireframes: false
      }
  });
  // create two boxes and a ground
var boxA = Bodies.rectangle(400, 200, 80, 80, {
  inertia: Infinity,
  frictionAir: 1
});
var boxB = Bodies.rectangle(450, 50, 80, 80);
var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });
var wall = Bodies.rectangle(0, 400, 60, 810, { isStatic: true });
// add all of the bodies to the world
Composite.add(engine.world, [boxA, boxB, ground,wall ]);

// run the renderer
Render.run(render);

// create runner
var runner = Runner.create();
log(render)
// run the engine
Runner.run(runner, engine);
let mouse = Mouse.create(render.canvas)
let mouseConstraint = MouseConstraint.create(engine,{
  mouse: mouse,
  constraint:{
    stiffness: 0.2,
    render:{
      visible: false
    }
  }
})
Events.on(mouseConstraint, "mousemove", (e)=>{
  boxA.position.y =  e.mouse.position.y
})
Composite.add(engine.world, [mouseConstraint]);

  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>

        </main>
    </>
  )
}
